### PR TITLE
feat: upgrade to `embedded-hal@1.0`

### LINKED ISSUE #25: `embedded-hal@1.0` traits implementation

### PR DESCRIPTION
**Pull request by elpiel**
Closes #25

### CODE REVIEW

**Comment by rnestler** [comment]
The CI integration with GitHub seems broken, but the CI run on CircleCI seemed to fail: https://app.circleci.com/pipelines/github/Sensirion/sensirion-i2c-rs/76/workflows/bb147492-bd3c-4556-809c-9c0d46cb975c/jobs/72

I guess the MSRV needs to be increased.

**Comment by elpiel** [comment]
Yes, that's correct. I can increase it, should we aim at the lowest possible MSRV or should we bump to 2-3 major versions ago?

**Comment by psachs** [comment]
I updated rustc to 1.63 which is the oldest version that supports embedded-hal 1.0. The circle-ci integration should also work again.
The pull request is here. Feel free to add this small change to your PR to fix the CI
https://github.com/Sensirion/sensirion-i2c-rs/pull/27

**Comment by elpiel** [comment]
Thanks @psachs !

**Review by psachs — APPROVED** [review]

**Pull request merged**
